print("Getting to know you!")
print()
Myname = input("what's your name?: ")
Myfavouritefood = input("What's your favourite food?: ")
Myfavouritemusic = input("What's your favourite music?: ")
Myplace = input("Where do you live?: ")
print()
print("You are")
print(Myname)
print("You're probably hungry for")
print(Myfavouritefood)
print("and you're definitely getting your groove on to")
print(Myfavouritemusic)
print("living in the amazing")
print(Myplace)